### ISSUE TITLE
Tutorial Data failing

### ISSUE THREAD

**Issue by hansenbry** [mxhulab/cryosieve#35]
Hi - I've been following the install and setup instruction on the main page, but when testing the 'Toy' demo set I'm getting an error:

(CRYOSIEVE_ENV) [hansenbry@##### toy]$ cryosieve-core --i CNG.star --o Myoutputs/Bryan_CNG_Test.star --angpix 1.32 --volume CNG_A.mrc --volume CNG_B.mrc --mask CNG_mask.mrc --retention_ratio 0.8 --frequency 40 --balance --num_gpus 2
usage: cryosieve-core [-h] --i I --o O [--directory DIRECTORY] [--angpix ANGPIX] --volume VOLUME [--mask MASK] --retention_ratio RETENTION_RATIO --frequency FREQUENCY [--num_gpus NUM_GPUS]
cryosieve-core: error: unrecognized arguments: --balance
(CRYOSIEVE_ENV) [hansenbry@ai-rmlcpu24 toy]$ cryosieve-core --i CNG.star --o Myoutputs/Bryan_CNG_Test.star --angpix 1.32 --volume CNG_A.mrc --volume CNG_B.mrc --mask CNG_mask.mrc --retention_ratio 0.8 --frequency 40 --num_gpus 2
Traceback (most recent call last):
  File "/gs1/home/hansenbry/.conda/envs/CRYOSIEVE_ENV/bin/cryosieve-core", line 8, in <module>
    sys.exit(core())
  File "/gs1/home/hansenbry/.conda/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/core.py", line 92, in core
    core_args = f'--i {args.i} --o {args.o} {f"--directory {args.directory}" if args.directory else ""} --angpix {args.angpix} {" ".join([f"--volume {volume}" for volume in args.volume])} {f"--mask {args.mask}" if args.mask is not None else ""} --retention_ratio {args.retention_ratio} --frequency {args.frequency} {"--balance" if args.balance else ""}'
AttributeError: 'Namespace' object has no attribute 'balance'

Any advice as to what I did wrong or which step I missed? Thanks!

**Comment by Zarrathustra** [comment]
Please refer to this issue: https://github.com/mxhulab/cryosieve/issues/32.

It seems you’re encountering a bug introduced in CryoSieve v1.2.6, which we have fixed in v1.2.8. Please check your version and upgrade if you’re using a version older than v1.2.8.

**Comment by hansenbry** [comment]
Hi @Zarrathustra thanks for the tip. I didn't specify any version when I did the pip install so assumed it would be the newest version. I don't see an option for displaying the version of cryosieve I have installed. Is there a command for that or what's the best way to make sure I'm installing the newest version of cryosieve

**Comment by hansenbry** [comment]
Also after making sure I have v 1.2.8 I'm still getting an error in the tutorial data

(CRYOSIEVE_v1.8) [hansenbry@#### toy]$ cryosieve-core --i CNG.star --o my_CNG_1.star --angpix 1.32 --volume CNG_A.mrc --volume CNG_B.mrc --mask CNG_mask.mrc --retention_ratio 0.8 --freq                               uency 40
Traceback (most recent call last):
  File "/gs1/home/hansenbry/.conda/envs/CRYOSIEVE_v1.8/bin/cryosieve-core", line 8, in <module>
    sys.exit(core())
  File "/gs1/home/hansenbry/.conda/envs/CRYOSIEVE_v1.8/lib/python3.10/site-packages/cryosieve/core.py", line 88, in core
    main(args)
  File "/gs1/home/hansenbry/.conda/envs/CRYOSIEVE_v1.8/lib/python3.10/site-packages/cryosieve/core.py", line 42, in main
    dataset     = ParticleDataset(args.i, args.directory, args.angpix)
  File "/gs1/home/hansenbry/.conda/envs/CRYOSIEVE_v1.8/lib/python3.10/site-packages/cryosieve/ParticleDataset.py", line 62, in __init__
    raise ValueError('Invalid particle star file.')
ValueError: Invalid particle star file.

**Comment by zerinf** [comment]
Hi, hansenbry. I just ran the toy example with version 1.2.8 in my laptop without any error. You may check if there is anything wrong in your downloaded star file?

**Comment by Zarrathustra** [comment]
@hansenbry If you have checked the star file, we look forward to your feedback.
